#pragma once
#include <vector>
#include <string>

std::vector<std::string> hardcodedEntries = {
	//HL2
	"scenes/Expressions/BarneyAlert.vcd",
"scenes/Expressions/BarneyCombat.vcd",
"scenes/Expressions/BarneyIdle.vcd",
"scenes/Expressions/CitizenAlert_loop.vcd",
"scenes/Expressions/CitizenCombat_loop.vcd",
"scenes/Expressions/CitizenIdle.vcd",
"scenes/Expressions/FishermanAlert.vcd",
"scenes/Expressions/FishermanCombat.vcd",
"scenes/Expressions/FishermanIdle.vcd",
"scenes/Expressions/citizen_angry_alert_01.vcd",
"scenes/Expressions/citizen_angry_combat_01.vcd",
"scenes/Expressions/citizen_angry_idle_01.vcd",
"scenes/Expressions/citizen_normal_alert_01.vcd",
"scenes/Expressions/citizen_normal_combat_01.vcd",
"scenes/Expressions/citizen_normal_idle_01.vcd",
"scenes/Expressions/citizen_scared_alert_01.vcd",
"scenes/Expressions/citizen_scared_combat_01.vcd",
"scenes/Expressions/citizen_scared_idle_01.vcd",
"scenes/expressions/citizenalert_loop.vcd",
"scenes/expressions/citizencombat_loop.vcd",
"scenes/expressions/citizenidle.vcd",
//EP2
"scenes/npc/hunter/hunter_eyeclose.vcd",
"scenes/npc/hunter/hunter_eyedarts_bottom.vcd",
"scenes/npc/hunter/hunter_eyedarts_top.vcd",
"scenes/npc/hunter/hunter_pain.vcd",
"scenes/npc/hunter/hunter_roar.vcd",
"scenes/npc/hunter/hunter_scan.vcd",

//Portal
"scenes/general/generic_security_camera_destroyed-1.vcd",
"scenes/general/generic_security_camera_destroyed-2.vcd",
"scenes/general/generic_security_camera_destroyed-3.vcd",
"scenes/general/generic_security_camera_destroyed-4.vcd",
"scenes/general/generic_security_camera_destroyed-5.vcd",

//Portal 2
"scenes/npc/sp_proto_sphere/sphere_plug_attach.vcd",
"scenes/npc/sp_proto_sphere/sphere_plug_lock.vcd",

//TF2
"scenes/bot/merasmus/low/bomb_attack_001.vcd",
"scenes/bot/merasmus/low/bomb_attack_002.vcd",
"scenes/bot/merasmus/low/bomb_attack_003.vcd",
"scenes/bot/merasmus/low/bomb_attack_004.vcd",
"scenes/bot/merasmus/low/bomb_attack_005.vcd",
"scenes/bot/merasmus/low/bomb_attack_006.vcd",
"scenes/bot/merasmus/low/bomb_attack_007.vcd",
"scenes/bot/merasmus/low/bomb_attack_008.vcd",
"scenes/bot/merasmus/low/bomb_attack_009.vcd",
"scenes/player/demoman/low/954.vcd",
"scenes/player/demoman/low/taunt09.vcd",
"scenes/player/engineer/low/103.vcd",
"scenes/player/engineer/low/taunt07.vcd",
"scenes/player/engineer/low/taunt09.vcd",
"scenes/player/engineer/low/taunt_drg_melee.vcd",
"scenes/player/heavy/low/270.vcd",
"scenes/player/heavy/low/taunt03_v1.vcd",
"scenes/player/medic/low/608.vcd",
"scenes/player/medic/low/taunt06.vcd",
"scenes/player/medic/low/taunt08.vcd",
"scenes/player/pyro/low/1485.vcd",
"scenes/player/pyro/low/taunt01_v1.vcd",
"scenes/player/pyro/low/taunt01_v2.vcd",
"scenes/player/pyro/low/taunt01_v3.vcd",
"scenes/player/pyro/low/taunt02.vcd",
"scenes/player/pyro/low/taunt_bubbles.vcd",
"scenes/player/pyro/low/taunt_scorch_shot.vcd",
"scenes/player/scout/low/435.vcd",
"scenes/player/scout/low/taunt05_v1.vcd",
"scenes/player/sniper/low/1674.vcd",
"scenes/player/sniper/low/taunt04.vcd",
"scenes/player/soldier/low/1346.vcd",
"scenes/player/soldier/low/taunt05.vcd",
"scenes/player/spy/low/1312.vcd",
"scenes/player/spy/low/taunt03_v1.vcd",
"scenes/player/spy/low/taunt03_v2.vcd",
"scenes/heavy_test.vcd",
};
